<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://v8.fsk.ru/kfk/test/1.0" targetNamespace="http://v8.fsk.ru/kfk/test/1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:simpleType name="TestAccumulationRegister.Period">
    <xs:restriction base="xs:dateTime"/>
  </xs:simpleType>
  <xs:simpleType name="TestAccumulationRegister.Value">
    <xs:restriction base="xs:decimal"/>
  </xs:simpleType>
  <xs:simpleType name="TestCatalog.Boolean">
    <xs:restriction base="xs:boolean"/>
  </xs:simpleType>
  <xs:simpleType name="TestCatalog.Comment">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>
  <xs:simpleType name="TestCatalog.DateTime">
    <xs:restriction base="xs:dateTime"/>
  </xs:simpleType>
  <xs:simpleType name="TestCatalog.Enum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Значение1"/>
      <xs:enumeration value="Значение2"/>
      <xs:enumeration value="Значение3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TestCatalog.Name">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>
  <xs:simpleType name="TestCatalog.Number">
    <xs:restriction base="xs:decimal"/>
  </xs:simpleType>
  <xs:simpleType name="TestCatalog.TabularSection.Row.DateTime">
    <xs:restriction base="xs:dateTime"/>
  </xs:simpleType>
  <xs:simpleType name="TestCatalog.TabularSection.Row.String">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>
  <xs:simpleType name="TestRegister.Boolean">
    <xs:restriction base="xs:boolean"/>
  </xs:simpleType>
  <xs:simpleType name="TestRegister.Comment">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>
  <xs:simpleType name="TestRegister.DateTime">
    <xs:restriction base="xs:dateTime"/>
  </xs:simpleType>
  <xs:simpleType name="TestRegister.Number">
    <xs:restriction base="xs:decimal"/>
  </xs:simpleType>
  <xs:simpleType name="TestRegister.Period">
    <xs:restriction base="xs:dateTime"/>
  </xs:simpleType>
  <xs:simpleType name="TestRegister.String">
    <xs:restriction base="xs:string">
      <xs:maxLength value="50"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TestRegister.Uuid">
    <xs:restriction base="xs:string">
      <xs:minLength value="36"/>
      <xs:maxLength value="36"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TestRegisterRs.Period">
    <xs:restriction base="xs:dateTime"/>
  </xs:simpleType>
  <xs:simpleType name="TestRegisterRs.Value">
    <xs:restriction base="xs:decimal"/>
  </xs:simpleType>
  <xs:simpleType name="UUID">
    <xs:annotation>
      <xs:documentation>UUID identifier</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:length value="36"/>
      <xs:pattern value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="TestAccumulationRegister">
    <xs:sequence>
      <xs:element name="period" type="tns:TestAccumulationRegister.Period" minOccurs="1" maxOccurs="1" nillable="false"/>
      <xs:element name="recorder" type="tns:UUID" minOccurs="1" maxOccurs="1" nillable="false"/>
      <xs:element name="id" type="tns:UUID" minOccurs="1" maxOccurs="1" nillable="false"/>
      <xs:element name="value" type="tns:TestAccumulationRegister.Value" minOccurs="0" maxOccurs="1" nillable="false"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TestCatalog">
    <xs:sequence>
      <xs:element name="ref" type="tns:UUID" minOccurs="1" maxOccurs="1" nillable="false"/>
      <xs:element name="name" type="tns:TestCatalog.Name" minOccurs="1" maxOccurs="1" nillable="false"/>
      <xs:element name="dateTime" type="tns:TestCatalog.DateTime" minOccurs="0" maxOccurs="1" nillable="false"/>
      <xs:element name="number" type="tns:TestCatalog.Number" minOccurs="0" maxOccurs="1" nillable="false"/>
      <xs:element name="boolean" type="tns:TestCatalog.Boolean" minOccurs="0" maxOccurs="1" nillable="false"/>
      <xs:element name="enum" type="tns:TestCatalog.Enum" minOccurs="0" maxOccurs="1" nillable="false"/>
      <xs:element name="comment" type="tns:TestCatalog.Comment" minOccurs="0" maxOccurs="1" nillable="false"/>
      <xs:element name="tabularSection" type="tns:TestCatalog.TabularSection" minOccurs="0" maxOccurs="1" nillable="false"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TestCatalog.TabularSection">
    <xs:sequence>
      <xs:element name="row" type="tns:TestCatalog.TabularSection.Row" minOccurs="0" maxOccurs="unbounded" nillable="false"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TestCatalog.TabularSection.Row">
    <xs:sequence>
      <xs:element name="dateTime" type="tns:TestCatalog.TabularSection.Row.DateTime" minOccurs="0" maxOccurs="1" nillable="false"/>
      <xs:element name="string" type="tns:TestCatalog.TabularSection.Row.String" minOccurs="0" maxOccurs="1" nillable="false"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TestRegister">
    <xs:sequence>
      <xs:element name="period" type="tns:TestRegister.Period" minOccurs="1" maxOccurs="1" nillable="false"/>
      <xs:element name="testRef" type="tns:UUID" minOccurs="0" maxOccurs="1" nillable="false"/>
      <xs:element name="boolean" type="tns:TestRegister.Boolean" minOccurs="0" maxOccurs="1" nillable="false"/>
      <xs:element name="string" type="tns:TestRegister.String" minOccurs="0" maxOccurs="1" nillable="false"/>
      <xs:element name="number" type="tns:TestRegister.Number" minOccurs="0" maxOccurs="1" nillable="false"/>
      <xs:element name="dateTime" type="tns:TestRegister.DateTime" minOccurs="0" maxOccurs="1" nillable="false"/>
      <xs:element name="uuid" type="tns:TestRegister.Uuid" minOccurs="0" maxOccurs="1" nillable="false"/>
      <xs:element name="comment" type="tns:TestRegister.Comment" minOccurs="0" maxOccurs="1" nillable="false"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TestRegisterRs">
    <xs:sequence>
      <xs:element name="period" type="tns:TestRegisterRs.Period" minOccurs="1" maxOccurs="1" nillable="false"/>
      <xs:element name="recorder" type="tns:UUID" minOccurs="1" maxOccurs="1" nillable="false"/>
      <xs:element name="id" type="tns:UUID" minOccurs="1" maxOccurs="1" nillable="false"/>
      <xs:element name="value" type="tns:TestRegisterRs.Value" minOccurs="0" maxOccurs="1" nillable="false"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
