#============================================================
# 🧩 Fluent Bit Configuration
#============================================================

[SERVICE]
    Flush                     1
    Daemon                    Off
    Log_Level                 info
    Parsers_File              parsers.conf

#------------------------------------------------------------
# 🌐 HTTP Input
#------------------------------------------------------------
[INPUT]
    Name                      http
    Listen                    0.0.0.0
    Port                      9880
    successful_response_code  200
    buffer_chunk_size         2M
    buffer_max_size           20M

#------------------------------------------------------------
# 🧪 Filter: применяем parser к полю @timestamp
#------------------------------------------------------------
[FILTER]
    Name          parser
    Match         *
    Key_Name      @timestamp
    Parser        extract_index_ts
    Reserve_Data  On
    Preserve_Key  On

#------------------------------------------------------------
# 📤 Output to OpenSearch
#------------------------------------------------------------
[OUTPUT]
    Name                      opensearch
    Match                     *
    Host                      opensearch
    Port                      9200

    Index                     $logger.$index_ts

    Id_Key                    id
    Write_Operation            upsert
    Suppress_Type_Name         On
    Replace_Dots               On
    Trace_Error                On

    Buffer_Size                6M
    Retry_Limit                False

