input {
    http {
        host => "0.0.0.0"
        port => 8080
        codec => "json"
  }
}

filter {
    date {
        match => ["@timestamp", "ISO8601"]
        target => "@timestamp"
        remove_field => ["_dateparsefailure"]
    }

    mutate {
        add_field => {
            "[@metadata][id]" => "%{id}"
            "[@metadata][index]" => "%{logger}"
        }
    }

    mutate { remove_field => ["logger", "id"] }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "%{[@metadata][index]}-%{+yyyy.MM.dd}"
        action => "update"
        document_id => "%{[@metadata][id]}"
        doc_as_upsert => true
    }
}
